#
# dotphiles : https://github.com/dotphiles/dotphiles
#
# Defines environment variables.
#
# Authors:
#   Ben O'Hara <bohara@gmail.com>
#

# Dont read global configs
unsetopt GLOBAL_RCS

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Customize to your needs...

export DEFAULT_USER=inayd
export EDITOR="vim"

export DONOTMODIFYPROMPT=Y
export CRL_PATH_QT_ROOT=$HOME/Qt
export WALDOROOT=~/waldo/trunk/source
export PATH="$WALDOROOT/Common/bin/mac:$PATH"
export USE_CCACHE=Y
export CCACHE_CPP2=yes
export CCACHE_SLOPPINESS=time_macros
export MKBOX=Simple
export MKTYPE=DEBUG
export MK_HIDE_PRAGMA_MESSAGE=Y
